Repository amysiu1028/FitLit, pull requests merged in 2023-10, with the labels that each got.

#33 Feature/skeleton html css ben
  dist/index.html
  src/css/styles.css
Labels: enhancement

#36 style: add additional CSS to meet mininum viable product
  dist/index.html
Labels: enhancement

#37 Feature/dom iteration one
  dist/index.html
  src/data/sampleData.js
  src/domUpdates.js
  src/hydrationFunctions.js
  src/scripts.js
  src/styles.css
Labels: documentation, enhancement

#43 Feature/average fluid per day
  src/data/hydration.js
  src/domUpdates.js
  src/hydrationFunctions.js
  src/sampleData.js
  src/scripts.js
Labels: enhancement

#48 Feature/average sleep day
  dist/bundle.js
  src/data-model.js
  src/scripts.js
Labels: enhancement

#49 Adjust getOuncesPerWeek function to allow for date sorting
  src/data-model.js
  src/hydrationFunctions.js
  src/scripts.js
Labels: enhancement

#51 Feature/average sleep overall
  dist/index.html
  src/data-model.js
  src/domUpdates.js
  src/sampleSleep.js
  src/scripts.js
Labels: enhancement

#53 Feature/hours slept specific day
  dist/index.html
  src/data-model.js
  src/domUpdates.js
  src/scripts.js
Labels: bug

#56 Feature/skeleton html css ben
  dist/index.html
  src/styles.css
Labels: enhancement

#59 Feature/fetch call emalee
  src/apiCalls.js
  src/data-model.js
  src/domUpdates.js
  src/hydrationFunctions.js
  src/scripts.js
Labels: enhancement

#63 Feature/sleep quality week
  src/data-model.js
  src/domUpdates.js
  src/scripts.js
Labels: enhancement

#62 Feature/tests iteration one two four
  src/data-model.js
  src/data/sampleData.js
  src/hydrationFunctions.js
  src/images/turing-logo.png
  test/ActivityRepository-tests.js
  test/HydrationRepository-tests.js
  test/SleepRepository-tests.js
  test/UserRepository-test.js
Labels: documentation, enhancement

#72 Test/api calls
  package.json
  src/apiCalls.js
  src/data/hydration.js
  src/data/users.js
  src/sampleData.js
  src/sampleSleep.js
Labels: enhancement

#75 feat/Make color palette match accessibility
  src/styles.css
Labels: enhancement

#76 Feature/chart
  dist/index.html
  src/data-model.js
  src/domUpdates.js
  src/scripts.js
  src/styles.css
Labels: enhancement

#78 Feature/skeleton html css ben
  dist/index.html
  src/data-model.js
  src/domUpdates.js
  src/styles.css
Labels: enhancement

#79 Feature/update color palette
  dist/index.html
  src/data-model.js
  src/domUpdates.js
  src/styles.css
Labels: enhancement

#80 Feature/skeleton html css ben
  src/data-model.js
  src/styles.css
Labels: enhancement

#81 feat/Add sleeping chart with sleep quality and update user info so al…
  dist/index.html
  src/data-model.js
  src/domUpdates.js
  src/scripts.js
  src/styles.css
Labels: enhancement

#85 Feature/activity chart
  src/data-model.js
  src/domUpdates.js
  src/scripts.js
  src/styles.css
Labels: enhancement

#89 Feature/fix chart data
  src/data-model.js
  src/domUpdates.js
  src/hydrationFunctions.js
  src/scripts.js
Labels: enhancement

#88 Add additional styling to charts and right side container
  dist/index.html
  src/styles.css
Labels: enhancement

#91 Feature/refactor display function
  dist/index.html
  src/domUpdates.js
  src/hydrationFunctions.js
  src/scripts.js
Labels: refactor

#92 Feature/header date
  dist/index.html
  src/domUpdates.js
  src/scripts.js
Labels: enhancement

#93 feat/Change sentence structure
  src/domUpdates.js
Labels: enhancement

#95 Test/finish fix remaining
  dist/index.html
  src/data-model.js
  test/ActivityRepository-tests.js
  test/HydrationRepository-tests.js
  test/SleepRepository-tests.js
  test/UserRepository-test.js
Labels: documentation, enhancement

#96 feat/Update CSS to prevent overflow on username and steps paragraph
  dist/index.html
  src/styles.css
Labels: enhancement

#109 Feature/dry functions
  src/data-model.js
  src/scripts.js
Labels: enhancement

#110 Fix/accessibility
  dist/index.html
  src/styles.css
Labels: enhancement
