Repository amysiu1028/FitLit, pull requests merged in 2023-11, with the labels that each got.

#118 Feature/fix tests move files
  src/apiCalls.js
  src/charts.js
  src/data-model.js
  src/hydrationFunctions.js
  src/scripts.js
  test/ActivityRepository-tests.js
  test/HydrationRepository-tests.js
  test/SleepRepository-tests.js
  test/UserRepository-test.js
Labels: documentation, enhancement

#119 Feature/double declaration
  src/data-model.js
  src/scripts.js
Labels: enhancement

#121 Feature/update water chart
  src/apiCalls.js
  src/charts.js
  src/data-model.js
  src/scripts.js
Labels: enhancement

#123 Change color of form labels to white
  src/styles.css
Labels: enhancement

#130 Add chart titles and aria labels
  dist/index.html
Labels: enhancement

#131 Refactor/code cleanup
  src/apiCalls.js
  src/data-model.js
  src/scripts.js
Labels: refactor

#134 Fix/tests not passing
  src/apiCalls.js
  src/data-model.js
  src/scripts.js
  src/styles.css
  test/ActivityRepository-tests.js
  test/HydrationRepository-tests.js
  test/UserRepository-test.js
Labels: documentation, enhancement

#135 Feature/form error
  dist/index.html
  src/apiCalls.js
  src/styles.css
Labels: enhancement

#136 Feature/finish accessibility
  dist/index.html
  src/styles.css
Labels: documentation, enhancement

#140 Fix/calendar display twice
  dist/index.html
  package.json
  src/scripts.js
Labels: bug

#143 Feat/server error message
  dist/index.html
  src/apiCalls.js
  src/styles.css
Labels: enhancement
